# permissions for end users to view grafanausers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-viewer-role
rules:
- apiGroups:
  - grafana.snappcloud.io
  resources:
  - grafanausers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - grafana.snappcloud.io
  resources:
  - grafanausers/status
  verbs:
  - get
